// <auto-generated />
namespace ArchivoUH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class all_migrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(all_migrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201907080417495_all_migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
